openapi: 3.1.0

info:
  title: Retaia Core API
  version: 1.0.0
  description: |
    Normative OpenAPI v1 for Retaia Core.

    This API coordinates assets, processing jobs and agents.
    Agents are non-reliable by design.
    Jobs may remain pending indefinitely if no compatible agent is available.

servers:
  - url: /api/v1

tags:
  - name: Assets
  - name: Agents
  - name: Jobs
  - name: Derived

paths:

  /agents/register:
    post:
      tags: [Agents]
      summary: Register a processing agent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [agent_name, agent_version, capabilities]
              properties:
                agent_name:
                  type: string
                agent_version:
                  type: string
                platform:
                  type: string
                capabilities:
                  type: array
                  items:
                    type: string
                max_parallel_jobs:
                  type: integer
      responses:
        "200":
          description: Agent registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent_id:
                    type: string
                  server_policy:
                    type: object

  /jobs:
    get:
      tags: [Jobs]
      summary: List claimable jobs for the authenticated agent
      description: |
        Returns jobs with status `pending`
        and compatible with the agent capabilities.
      responses:
        "200":
          description: List of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Job"

  /jobs/{job_id}/claim:
    post:
      tags: [Jobs]
      summary: Claim a job (atomic lease)
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Job claimed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"
        "409":
          description: Job not claimable

  /jobs/{job_id}/heartbeat:
    post:
      tags: [Jobs]
      summary: Extend job lease
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [lock_token]
              properties:
                lock_token:
                  type: string
      responses:
        "200":
          description: Lease extended
          content:
            application/json:
              schema:
                type: object
                properties:
                  locked_until:
                    type: string
                    format: date-time

  /jobs/{job_id}/submit:
    post:
      tags: [Jobs]
      summary: Submit job result
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobResult"
      responses:
        "200":
          description: Job completed
        "423":
          description: Invalid or missing lock

  /jobs/{job_id}/fail:
    post:
      tags: [Jobs]
      summary: Mark job as failed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [lock_token, error_code, retryable]
              properties:
                lock_token:
                  type: string
                error_code:
                  type: string
                message:
                  type: string
                retryable:
                  type: boolean
      responses:
        "200":
          description: Job failed recorded

components:

  schemas:

    Job:
      type: object
      description: Processing job
      required:
        - job_id
        - job_type
        - status
        - asset_uuid
        - required_capabilities
      properties:
        job_id:
          type: string
        job_type:
          type: string
        status:
          type: string
          enum: [pending, claimed, completed, failed]
        asset_uuid:
          type: string
        required_capabilities:
          type: array
          items:
            type: string
        claimed_by:
          type: string
          nullable: true
        locked_until:
          type: string
          format: date-time
          nullable: true

    JobResult:
      type: object
      required: [lock_token, success]
      properties:
        lock_token:
          type: string
        success:
          type: boolean
        output:
          type: object
          additionalProperties: true
        errors:
          type: array
          items:
            type: string